docs: Convert mentions of `do-not-evict` to `do-not-disrupt`
aws/karpenter-provider-aws pull request #7539
Opened 2024-12-17 23:55 UTC by trevenrawr

Fixes #N/A 

The Troubleshooting docs were out of date with v1.0+ (as per this post mentioning deprecation of the `do-not-evict` annotation.)  Figured I'd clean that up to reduce confusion!

NOTE: I'm not entirely sure how this works with already published docs versions, so any guidance there would be quite welcome.  Thanks!

Probably doesn't need testing?

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-18 20:31 UTC, engedaam approved these changes
LGTM 🚀

2024-12-18 20:32 UTC, engedaam commented on website/content/en/docs/troubleshooting.md
> +#### `karpenter.sh/do-not-disrupt` Annotation
Can we also make this change to preview and 1.1 version of the docs?

2024-12-18 20:33 UTC, engedaam requested changes
Can we also make this change to preview and 1.1 version of the docs?

2025-01-02 17:23 UTC, trevenrawr commented
Update: Found it!  Given the changes elsewhere, should I remove the changes to `docs/troubleshooting` ?

2025-01-07 18:13 UTC, engedaam commented
No, we should keep the changes in the docs folder

2025-01-07 18:13 UTC, engedaam approved these changes
LGTM 🚀

2025-01-07 18:19 UTC, merged