test: added a test where there is no ips
aws/karpenter-provider-aws pull request #7549
Opened 2024-12-21 16:34 UTC by Summonair

Fixes #N/A 

**Description**

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-21 16:40 UTC, Summonair commented
this pr is adding a test before merging #7310, which fixes issues #5234 , #2921 
@rschalo i've added the test you asked in https://github.com/aws/karpenter-provider-aws/pull/7310#issuecomment-2546405177

2024-12-22 14:50 UTC, Vacant2333 commented
thank u for this!
/assign

2024-12-23 02:41 UTC, Vacant2333 approved these changes
/lgtm
this looks good to me,thanks!

2024-12-23 21:50 UTC, Summonair commented
@jigisha620 Hey, when you get a chance, it would mean a lot if you could take a quick look at this PR. I know you’re busy, but your feedback would be really valuable to us (me and @Vacant2333)

2025-01-03 02:53 UTC, Vacant2333 commented
@rschalo hi, can u help us to review this pr? its really important for the issue https://github.com/aws/karpenter-provider-aws/issues/5234

2025-01-14 23:49 UTC, engedaam commented
@Summonair This change should really be in PR: https://github.com/aws/karpenter-provider-aws/pull/7310, since we will need to wait until that PR is merged before pushing this change. Also seems like we have failures not related to Karpenter behavior in the test

2025-01-15 02:09 UTC, Vacant2333 commented
@engedaam Can we merge [#7310](https://github.com/aws/karpenter-provider-aws/pull/7310) first and add ut later?

2025-01-22 20:34 UTC, saurav-agarwalla requested changes
Please bring these changes to https://github.com/aws/karpenter-provider-aws/pull/7310.

2025-01-22 21:39 UTC, Summonair commented
> Please bring these changes to #7310.

hey, i fixed the ci errors, how can i merge to his pr?
@Vacant2333 can u add me push perms on your fork so i can create a branch on yours?

2025-01-23 01:50 UTC, Vacant2333 commented
@Summonair Thanks for you help!
I have invite u to my fork repo, u should be able to push and create a branch on my fork
ref: https://github.com/Vacant2333/karpenter-provider-aws

2025-01-23 18:01 UTC, saurav-agarwalla commented
Closing this in favor of https://github.com/aws/karpenter-provider-aws/pull/7623 so that we can track the discussions in a single thread.

2025-01-23 18:01 UTC, closed without merging